name: CI Simple

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint check
        id: lint
        run: npm run lint
        continue-on-error: true

      - name: TypeScript check
        id: typecheck
        run: npx tsc --noEmit --skipLibCheck
        continue-on-error: true

      - name: Run tests
        id: test
        run: npm test -- --run
        continue-on-error: true

      - name: Build application
        id: build
        run: npm run build
        continue-on-error: true

      - name: Create summary report
        if: always()
        run: |
          echo "### CI Summary Report" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Install | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ steps.lint.outcome }}" = "success" ]; then
            echo "| Lint | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Lint | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ steps.typecheck.outcome }}" = "success" ]; then
            echo "| TypeScript | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| TypeScript | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ steps.test.outcome }}" = "success" ]; then
            echo "| Tests | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Tests | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ steps.build.outcome }}" = "success" ]; then
            echo "| Build | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Build | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi